package TrabalhoPraticoII.Biblioteca;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

public class Painel extends javax.swing.JFrame {

    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAutores = new javax.swing.JPanel();
        scrollAutores = new javax.swing.JScrollPane();
        listAutores = new javax.swing.JList<>();
        lblAutores = new javax.swing.JLabel();
        btnAutCriar = new javax.swing.JButton();
        btnAutApagar = new javax.swing.JButton();
        panelClientes = new javax.swing.JPanel();
        scrollClientes = new javax.swing.JScrollPane();
        listClientes = new javax.swing.JList<>();
        lblClientes = new javax.swing.JLabel();
        btnCliCriar = new javax.swing.JButton();
        btnCliApagar = new javax.swing.JButton();
        panelEditora = new javax.swing.JPanel();
        scrollEditora = new javax.swing.JScrollPane();
        listObrasDaEditora = new javax.swing.JList<>();
        lblEditora = new javax.swing.JLabel();
        btnEdiCriar = new javax.swing.JButton();
        btnEdiApagar = new javax.swing.JButton();
        lblEditNomeDaEditora = new javax.swing.JLabel();
        lblEdiObrasDaEditora = new javax.swing.JLabel();
        lblEdiGerenciarObras = new javax.swing.JLabel();
        panelEditoras = new javax.swing.JPanel();
        scrollEditoras = new javax.swing.JScrollPane();
        listEditoras = new javax.swing.JList<>();
        lblEditoras = new javax.swing.JLabel();
        btnEdisCriar = new javax.swing.JButton();
        btnEdisApagar = new javax.swing.JButton();
        panelCriarObra = new javax.swing.JPanel();
        lblCriarObraNome = new javax.swing.JLabel();
        txfCriarObraNome = new javax.swing.JTextField();
        txfCriarObraAutores = new javax.swing.JTextField();
        lblCriarObraAutores = new javax.swing.JLabel();
        btnCriarObraAutoresAdd = new javax.swing.JButton();
        btnCriarObra = new javax.swing.JButton();
        lblCriarObraNumDePags = new javax.swing.JLabel();
        txfCriarObraNumDePags = new javax.swing.JTextField();
        panelPessoa = new javax.swing.JPanel();
        lblCriarPessoaNome = new javax.swing.JLabel();
        txfCriarPessoaNome = new javax.swing.JTextField();
        txfCriarPessoaIdade = new javax.swing.JTextField();
        lblCriarPessoaIdade = new javax.swing.JLabel();
        btnCriarPessoa = new javax.swing.JButton();
        tblCriarPessoaSobrenome = new javax.swing.JLabel();
        txfCriarPessoaSobrenome = new javax.swing.JTextField();
        javax.swing.JPanel panelAtualizarObra = new javax.swing.JPanel();
        lblCriarObraNome1 = new javax.swing.JLabel();
        txfCriarObraNome1 = new javax.swing.JTextField();
        txfCriarObraAutores1 = new javax.swing.JTextField();
        lblCriarObraAutores1 = new javax.swing.JLabel();
        btnCriarObraAutoresAdd1 = new javax.swing.JButton();
        btnCriarObra1 = new javax.swing.JButton();
        btnCriarObraAutoresRemover = new javax.swing.JButton();
        lblAtualizarObraNumDePags = new javax.swing.JLabel();
        txfAtualizarObraNumDePags = new javax.swing.JTextField();
        txfAtualizarObraNumDeExemplares = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAtualizarObraNumDeExemplares = new javax.swing.JButton();
        tabPane = new javax.swing.JTabbedPane();
        msgDica = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        menubar = new javax.swing.JMenuBar();
        menuGerenciar = new javax.swing.JMenu();
        menuGerAutores = new javax.swing.JMenuItem();
        menuGerClientes = new javax.swing.JMenuItem();
        menuGerEditoras = new javax.swing.JMenuItem();
        menuRegistrar = new javax.swing.JMenu();
        menuRegEmprestimo = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        listAutores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollAutores.setViewportView(listAutores);

        lblAutores.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblAutores.setText("Autores");

        btnAutCriar.setText("Criar");
        btnAutCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutCriarActionPerformed(evt);
            }
        });

        btnAutApagar.setText("Apagar");

        javax.swing.GroupLayout panelAutoresLayout = new javax.swing.GroupLayout(panelAutores);
        panelAutores.setLayout(panelAutoresLayout);
        panelAutoresLayout.setHorizontalGroup(
            panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollAutores)
                    .addGroup(panelAutoresLayout.createSequentialGroup()
                        .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutores)
                            .addGroup(panelAutoresLayout.createSequentialGroup()
                                .addComponent(btnAutCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAutApagar)))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAutoresLayout.setVerticalGroup(
            panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAutoresLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutCriar)
                    .addComponent(btnAutApagar))
                .addContainerGap())
        );

        listClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollClientes.setViewportView(listClientes);

        lblClientes.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblClientes.setText("Clientes");

        btnCliCriar.setText("Criar");
        btnCliCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliCriarActionPerformed(evt);
            }
        });

        btnCliApagar.setText("Apagar");

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollClientes)
                    .addGroup(panelClientesLayout.createSequentialGroup()
                        .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClientes)
                            .addGroup(panelClientesLayout.createSequentialGroup()
                                .addComponent(btnCliCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCliApagar)))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClientesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCliCriar)
                    .addComponent(btnCliApagar))
                .addContainerGap())
        );

        listObrasDaEditora.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollEditora.setViewportView(listObrasDaEditora);

        lblEditora.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblEditora.setText("Editora");

        btnEdiCriar.setText("Criar");

        btnEdiApagar.setText("Apagar");

        lblEditNomeDaEditora.setText("nome da editora");

        lblEdiObrasDaEditora.setText("Obras:");

        lblEdiGerenciarObras.setText("Gerenciar obras:");

        javax.swing.GroupLayout panelEditoraLayout = new javax.swing.GroupLayout(panelEditora);
        panelEditora.setLayout(panelEditoraLayout);
        panelEditoraLayout.setHorizontalGroup(
            panelEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditoraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollEditora)
                    .addGroup(panelEditoraLayout.createSequentialGroup()
                        .addGroup(panelEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEditoraLayout.createSequentialGroup()
                                .addComponent(lblEditora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEditNomeDaEditora))
                            .addGroup(panelEditoraLayout.createSequentialGroup()
                                .addComponent(btnEdiCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdiApagar))
                            .addComponent(lblEdiObrasDaEditora)
                            .addComponent(lblEdiGerenciarObras))
                        .addGap(0, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEditoraLayout.setVerticalGroup(
            panelEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditoraLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditora)
                    .addComponent(lblEditNomeDaEditora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdiObrasDaEditora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEdiGerenciarObras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEditoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdiCriar)
                    .addComponent(btnEdiApagar))
                .addContainerGap())
        );

        listEditoras.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollEditoras.setViewportView(listEditoras);

        lblEditoras.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblEditoras.setText("Editoras");

        btnEdisCriar.setText("Criar");
        btnEdisCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdisCriarActionPerformed(evt);
            }
        });

        btnEdisApagar.setText("Apagar");

        javax.swing.GroupLayout panelEditorasLayout = new javax.swing.GroupLayout(panelEditoras);
        panelEditoras.setLayout(panelEditorasLayout);
        panelEditorasLayout.setHorizontalGroup(
            panelEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollEditoras)
                    .addGroup(panelEditorasLayout.createSequentialGroup()
                        .addGroup(panelEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditoras)
                            .addGroup(panelEditorasLayout.createSequentialGroup()
                                .addComponent(btnEdisCriar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdisApagar)))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEditorasLayout.setVerticalGroup(
            panelEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditorasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblEditoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollEditoras, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEditorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdisCriar)
                    .addComponent(btnEdisApagar))
                .addContainerGap())
        );

        lblCriarObraNome.setText("Nome da obra:");

        txfCriarObraNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCriarObraNomeActionPerformed(evt);
            }
        });

        lblCriarObraAutores.setText("Adicionar autor(a) por id:");

        btnCriarObraAutoresAdd.setText("Adicionar");
        btnCriarObraAutoresAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarObraAutoresAddActionPerformed(evt);
            }
        });

        btnCriarObra.setText("Criar");

        lblCriarObraNumDePags.setText("Número de páginas:");

        javax.swing.GroupLayout panelCriarObraLayout = new javax.swing.GroupLayout(panelCriarObra);
        panelCriarObra.setLayout(panelCriarObraLayout);
        panelCriarObraLayout.setHorizontalGroup(
            panelCriarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriarObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCriarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCriarObraNome)
                    .addComponent(txfCriarObraAutores)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCriarObraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelCriarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriarObraAutoresAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnCriarObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelCriarObraLayout.createSequentialGroup()
                        .addGroup(panelCriarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCriarObraNumDePags)
                            .addComponent(lblCriarObraNome)
                            .addComponent(lblCriarObraAutores))
                        .addGap(0, 147, Short.MAX_VALUE))
                    .addComponent(txfCriarObraNumDePags))
                .addContainerGap())
        );
        panelCriarObraLayout.setVerticalGroup(
            panelCriarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriarObraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCriarObraNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarObraNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCriarObraAutores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarObraAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCriarObraAutoresAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCriarObraNumDePags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarObraNumDePags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnCriarObra)
                .addContainerGap())
        );

        lblCriarPessoaNome.setText("Nome:");

        lblCriarPessoaIdade.setText("Idade:");

        btnCriarPessoa.setText("Criar");

        tblCriarPessoaSobrenome.setText("Sobrenome:");

        javax.swing.GroupLayout panelPessoaLayout = new javax.swing.GroupLayout(panelPessoa);
        panelPessoa.setLayout(panelPessoaLayout);
        panelPessoaLayout.setHorizontalGroup(
            panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfCriarPessoaNome)
                    .addComponent(txfCriarPessoaIdade)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPessoaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCriarPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txfCriarPessoaSobrenome)
                    .addGroup(panelPessoaLayout.createSequentialGroup()
                        .addGroup(panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCriarPessoaNome)
                            .addComponent(lblCriarPessoaIdade)
                            .addComponent(tblCriarPessoaSobrenome))
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPessoaLayout.setVerticalGroup(
            panelPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCriarPessoaNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarPessoaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblCriarPessoaSobrenome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarPessoaSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCriarPessoaIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarPessoaIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCriarPessoa)
                .addContainerGap())
        );

        lblCriarObraNome1.setText("Nome da obra:");

        lblCriarObraAutores1.setText("Adicionar/remover autor(a) por id:");

        btnCriarObraAutoresAdd1.setText("Adicionar");
        btnCriarObraAutoresAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarObraAutoresAdd1ActionPerformed(evt);
            }
        });

        btnCriarObra1.setText("Criar");

        btnCriarObraAutoresRemover.setText("Remover");
        btnCriarObraAutoresRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarObraAutoresRemoverActionPerformed(evt);
            }
        });

        lblAtualizarObraNumDePags.setText("Número de páginas:");

        jLabel1.setText("Número de exemplares:");

        btnAtualizarObraNumDeExemplares.setText("Atualizar");

        javax.swing.GroupLayout panelAtualizarObraLayout = new javax.swing.GroupLayout(panelAtualizarObra);
        panelAtualizarObra.setLayout(panelAtualizarObraLayout);
        panelAtualizarObraLayout.setHorizontalGroup(
            panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtualizarObraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfAtualizarObraNumDePags)
                    .addComponent(txfCriarObraNome1)
                    .addComponent(txfCriarObraAutores1)
                    .addGroup(panelAtualizarObraLayout.createSequentialGroup()
                        .addGroup(panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCriarObraNome1)
                            .addComponent(lblCriarObraAutores1)
                            .addComponent(lblAtualizarObraNumDePags)
                            .addComponent(jLabel1))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizarObraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCriarObraAutoresAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCriarObraAutoresRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtualizarObraLayout.createSequentialGroup()
                        .addComponent(txfAtualizarObraNumDeExemplares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriarObra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAtualizarObraNumDeExemplares, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelAtualizarObraLayout.setVerticalGroup(
            panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtualizarObraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCriarObraNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarObraNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCriarObraAutores1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfCriarObraAutores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCriarObraAutoresAdd1)
                    .addComponent(btnCriarObraAutoresRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAtualizarObraNumDePags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAtualizarObraNumDePags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAtualizarObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfAtualizarObraNumDeExemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizarObraNumDeExemplares))
                .addGap(24, 24, 24)
                .addComponent(btnCriarObra1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Dica: \n- Em listas o clique permite-lhe ver o item e o clique-duplo permite-lhe atualizar os dados do item.");
        msgDica.setViewportView(jTextArea1);

        menuGerenciar.setText("Gerenciar");

        menuGerAutores.setText("Autores");
        menuGerAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerAutoresActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerAutores);

        menuGerClientes.setText("Clientes");
        menuGerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerClientesActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerClientes);

        menuGerEditoras.setText("Editoras");
        menuGerEditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerEditorasActionPerformed(evt);
            }
        });
        menuGerenciar.add(menuGerEditoras);

        menubar.add(menuGerenciar);

        menuRegistrar.setText("Registrar");

        menuRegEmprestimo.setText("Emprestimo");

        jMenuItem7.setText("Registrar");
        menuRegEmprestimo.add(jMenuItem7);

        jMenuItem8.setText("Remover");
        menuRegEmprestimo.add(jMenuItem8);

        menuRegistrar.add(menuRegEmprestimo);

        menubar.add(menuRegistrar);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addComponent(msgDica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgDica, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarObraAutoresAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarObraAutoresAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarObraAutoresAddActionPerformed

    private void btnCriarObraAutoresAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarObraAutoresAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarObraAutoresAdd1ActionPerformed

    private void btnCriarObraAutoresRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarObraAutoresRemoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarObraAutoresRemoverActionPerformed

    private void menuGerEditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerEditorasActionPerformed
        model_e.clear();
        for(Editora e : editoras){
            int id = model_e.getSize();
            model_e.add(id, String.valueOf(id) + e.getNomeDaEditora());
        }
        listEditoras.setModel(model_e);
        Util.addNovaAba(tabPane, panelEditoras, "Editoras");
    }//GEN-LAST:event_menuGerEditorasActionPerformed

    private void menuGerAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerAutoresActionPerformed
        model_a.clear();
        for(Pessoa a : autores){
            int id = model_a.getSize();
            model_a.add(id, String.valueOf(id) + a.getNome() + " " + a.getSobrenome());
        }
        listAutores.setModel(model_a);
        Util.addNovaAba(tabPane, panelAutores, "Autores");
    }//GEN-LAST:event_menuGerAutoresActionPerformed

    private void menuGerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerClientesActionPerformed
        model_c.clear();
        for(Pessoa c : clientes){
            int id = model_c.getSize();
            model_c.add(id, String.valueOf(id) + c.getNome() + " " + c.getSobrenome());
        }
        listClientes.setModel(model_c);
        Util.addNovaAba(tabPane, panelClientes, "Clientes");
    }//GEN-LAST:event_menuGerClientesActionPerformed

    private void txfCriarObraNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCriarObraNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCriarObraNomeActionPerformed

    private void btnAutCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutCriarActionPerformed
        Pessoa p = new Autor("A", "A", 18);
        autores.add(p);
        model_a.add(model_a.getSize(), String.valueOf(model_a.getSize()) + p.getNome() + " " + p.getSobrenome());
    }//GEN-LAST:event_btnAutCriarActionPerformed

    private void btnCliCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliCriarActionPerformed
        Pessoa p = new Cliente("C", "C", 18);
        clientes.add(p);
        model_c.add(model_c.getSize(), String.valueOf(model_c.getSize()) + p.getNome() + " " + p.getSobrenome());
    }//GEN-LAST:event_btnCliCriarActionPerformed

    private void btnEdisCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdisCriarActionPerformed
        try {
            Editora e = new Editora("E");
            editoras.add(e);
            model_e.add(model_e.getSize(), String.valueOf(model_e.getSize()) + e.getNomeDaEditora());
        } catch (Exception ex) {
            Logger.getLogger(Painel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEdisCriarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }
    
    private DefaultListModel 
            model_c = new DefaultListModel(),
            model_e = new DefaultListModel(), 
            model_a = new DefaultListModel();
    private ArrayList<Editora> editoras = new ArrayList<>();
    private ArrayList<Pessoa> clientes = new ArrayList<>(), autores = new ArrayList<>();
    private static Util util = new Util();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarObraNumDeExemplares;
    private javax.swing.JButton btnAutApagar;
    private javax.swing.JButton btnAutCriar;
    private javax.swing.JButton btnCliApagar;
    private javax.swing.JButton btnCliCriar;
    private javax.swing.JButton btnCriarObra;
    private javax.swing.JButton btnCriarObra1;
    private javax.swing.JButton btnCriarObraAutoresAdd;
    private javax.swing.JButton btnCriarObraAutoresAdd1;
    private javax.swing.JButton btnCriarObraAutoresRemover;
    private javax.swing.JButton btnCriarPessoa;
    private javax.swing.JButton btnEdiApagar;
    private javax.swing.JButton btnEdiCriar;
    private javax.swing.JButton btnEdisApagar;
    private javax.swing.JButton btnEdisCriar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAtualizarObraNumDePags;
    private javax.swing.JLabel lblAutores;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblCriarObraAutores;
    private javax.swing.JLabel lblCriarObraAutores1;
    private javax.swing.JLabel lblCriarObraNome;
    private javax.swing.JLabel lblCriarObraNome1;
    private javax.swing.JLabel lblCriarObraNumDePags;
    private javax.swing.JLabel lblCriarPessoaIdade;
    private javax.swing.JLabel lblCriarPessoaNome;
    private javax.swing.JLabel lblEdiGerenciarObras;
    private javax.swing.JLabel lblEdiObrasDaEditora;
    private javax.swing.JLabel lblEditNomeDaEditora;
    private javax.swing.JLabel lblEditora;
    private javax.swing.JLabel lblEditoras;
    private javax.swing.JList<String> listAutores;
    private javax.swing.JList<String> listClientes;
    private javax.swing.JList<String> listEditoras;
    private javax.swing.JList<String> listObrasDaEditora;
    private javax.swing.JMenuItem menuGerAutores;
    private javax.swing.JMenuItem menuGerClientes;
    private javax.swing.JMenuItem menuGerEditoras;
    private javax.swing.JMenu menuGerenciar;
    private javax.swing.JMenu menuRegEmprestimo;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JScrollPane msgDica;
    private javax.swing.JPanel panelAutores;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelCriarObra;
    private javax.swing.JPanel panelEditora;
    private javax.swing.JPanel panelEditoras;
    private javax.swing.JPanel panelPessoa;
    private javax.swing.JScrollPane scrollAutores;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JScrollPane scrollEditora;
    private javax.swing.JScrollPane scrollEditoras;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JLabel tblCriarPessoaSobrenome;
    private javax.swing.JTextField txfAtualizarObraNumDeExemplares;
    private javax.swing.JTextField txfAtualizarObraNumDePags;
    private javax.swing.JTextField txfCriarObraAutores;
    private javax.swing.JTextField txfCriarObraAutores1;
    private javax.swing.JTextField txfCriarObraNome;
    private javax.swing.JTextField txfCriarObraNome1;
    private javax.swing.JTextField txfCriarObraNumDePags;
    private javax.swing.JTextField txfCriarPessoaIdade;
    private javax.swing.JTextField txfCriarPessoaNome;
    private javax.swing.JTextField txfCriarPessoaSobrenome;
    // End of variables declaration//GEN-END:variables
}
